//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace myNETShop
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ShopEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ShopEntities object using the connection string found in the 'ShopEntities' section of the application configuration file.
        /// </summary>
        public ShopEntities() : base("name=ShopEntities", "ShopEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ShopEntities object.
        /// </summary>
        public ShopEntities(string connectionString) : base(connectionString, "ShopEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ShopEntities object.
        /// </summary>
        public ShopEntities(EntityConnection connection) : base(connection, "ShopEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ShopDB> ShopDB
        {
            get
            {
                if ((_ShopDB == null))
                {
                    _ShopDB = base.CreateObjectSet<ShopDB>("ShopDB");
                }
                return _ShopDB;
            }
        }
        private ObjectSet<ShopDB> _ShopDB;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ShopDB EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToShopDB(ShopDB shopDB)
        {
            base.AddObject("ShopDB", shopDB);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ShopDBModel", Name="ShopDB")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ShopDB : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ShopDB object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="productName">Initial value of the productName property.</param>
        /// <param name="itemsInStock">Initial value of the itemsInStock property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        public static ShopDB CreateShopDB(global::System.Decimal id, global::System.String productName, global::System.Double itemsInStock, global::System.Decimal price)
        {
            ShopDB shopDB = new ShopDB();
            shopDB.ID = id;
            shopDB.productName = productName;
            shopDB.itemsInStock = itemsInStock;
            shopDB.Price = price;
            return shopDB;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String productName
        {
            get
            {
                return _productName;
            }
            set
            {
                if (_productName != value)
                {
                    OnproductNameChanging(value);
                    ReportPropertyChanging("productName");
                    _productName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("productName");
                    OnproductNameChanged();
                }
            }
        }
        private global::System.String _productName;
        partial void OnproductNameChanging(global::System.String value);
        partial void OnproductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double itemsInStock
        {
            get
            {
                return _itemsInStock;
            }
            set
            {
                if (_itemsInStock != value)
                {
                    OnitemsInStockChanging(value);
                    ReportPropertyChanging("itemsInStock");
                    _itemsInStock = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("itemsInStock");
                    OnitemsInStockChanged();
                }
            }
        }
        private global::System.Double _itemsInStock;
        partial void OnitemsInStockChanging(global::System.Double value);
        partial void OnitemsInStockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                if (_Price != value)
                {
                    OnPriceChanging(value);
                    ReportPropertyChanging("Price");
                    _Price = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Price");
                    OnPriceChanged();
                }
            }
        }
        private global::System.Decimal _Price;
        partial void OnPriceChanging(global::System.Decimal value);
        partial void OnPriceChanged();

        #endregion

    
    }

    #endregion

    
}
